### ISSUE TITLE
Repository moved permanently

### ISSUE THREAD

**Issue by richard-kramer** [feniix/asdf-sops#11]
It looks like the SOPS repository moved from https://github.com/mozilla/sops to https://github.com/getsops/sops. As a result, the list-all `curl` call returns this JSON:

```json
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/40684033/releases",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

This does obviously not work for listing the actual versions. I suspect, installation versions does also break.

As a solution, the URL should be changed to the new one and the `curl`-call should follow redirects to not break when something like this happens again.

**Comment by log2** [comment]
Could you please fix this bug, using [PR](https://github.com/feniix/asdf-sops/pull/12) from @khassel?  Thank you

While installing specific versions still works, [our dependency management tool](https://github.com/log2/shell-common) breaks badly for sops tool (see [here](https://github.com/log2/shell-common/blob/main/lib/asdf.sh#L199) and following lines).

Maybe a common library for managing GitHub-hosted tools, useable across all asdf plugins, could be a good idea in order to factor out facilities like these (following redirects, etc.).  cc @fragolinux

**Comment by chrodriguez** [comment]
It's really important to approve provided PR, it fixes this issue... Thanks in advance

**Comment by fragolinux** [comment]
“That is not dead which can eternal lie, And with strange aeons even PRs may die”

**Comment by mdgreenwald** [comment]
Would be great to get #12 merged.
